changeLogFile=changelog.xml

# url: jdbc:postgresql://localhost:5432/postgres
# url: jdbc:postgresql://localhost:5433/postgres
# url: jdbc:postgresql://localhost:5434/postgres
username: postgres
password: secret

# liquibase.logLevel=INFO
liquibase.reports.enabled=false

liquibase.license.utility.enabled=true
liquibase.license.utility.logLevel=FINE
liquibase.license.utility.url=http://localhost:8123
liquibase.license.utility.trackingId=LLU_UAT
